version: '3.4'

services:
  app:
    container_name: avito_backend_trainee
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    container_name: avito_trainee_postgres
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avito-trainee
      PGDATA: /data/postgres

