version: '3.4'

services:
  app:
    container_name: avito_backend_trainee
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./config/.env

  postgres:
    container_name: avito_trainee_postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avito-trainee
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
